## 1.Business problem

* There is historical data of insurance claim cases (around 1,300+ cases).
* Each case involves bodily injury insurance claims from a specific region.
* Some claimants hire an attorney{lawyer}, while others do not.
* Hiring an attorney usually increases the settlement amount, which affects:
 1.  The cost to the insurance company
 2. The profitability of the insurer
* The insurance company wants to:
1. Predict the likelihood that a claimant will hire an attorney
2. Understand which types of customers are more likely to hire an attorney
* Based on these insights, the company wants to:
1. Design better insurance policies
2. Target different customer segments differently

## 2.Data collection

### 2.1 Import necessary libraries

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

### 2.2 Import dataset

In [2]:
claimants_data = pd.read_csv(filepath_or_buffer='claimants.csv')
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

### output / Target Variable (Dependent Variable)
ATTORNEY
### Input Variables (Independent Variables)
CASENUM		CLMSEX	CLMINSUR	SEATBELT	CLMAGE	LOSS

**Here we have input and specific output so it is supervised ML**

**Here output is Discrete , so this is classification problem.**

## 3.Data understandin:

### 3.1 perfor initial analysis:

In [5]:
claimants_data.shape

(1340, 7)

In [6]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [8]:
claimants_data.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [9]:
claimants_data.describe()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1340.000000,1340.000000,1328.000000,1299.000000,1292.000000,1151.000000,1340.000000
mean,11202.001493,0.488806,0.558735,0.907621,0.017028,28.414422,3.806307
std,9512.750796,0.500061,0.496725,0.289671,0.129425,20.304451,10.636903
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4177.000000,0.000000,0.000000,1.000000,0.000000,9.000000,0.400000
50%,8756.500000,0.000000,1.000000,1.000000,0.000000,30.000000,1.069500
75%,15702.500000,1.000000,1.000000,1.000000,0.000000,43.000000,3.781500
max,34153.000000,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

## 4.Data preparation:

### 4.1 Data cleaning : Handling null entries

In [3]:
claimants_data = claimants_data.dropna()
claimants_data  # remove missing values NAN

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [4]:
claimants_data.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

### 4.2 Splitting inputs and outputs

during data cleanin we need to apply our common sense

Here we are dropping CASENUM  {nothing but name } based on name we are not going to predeict they will hire attorney .. so dropping this CASENUM column

In [5]:
X = claimants_data.drop(labels = ["CASENUM","ATTORNEY"],axis =1)
X

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [6]:
y = claimants_data[["ATTORNEY"]]
y

      ATTORNEY
0            0
1            1
2            1
3            0
4            1
...        ...
1334         1
1336         0
1337         1
1338         0
1339         1

[1096 rows x 1 columns]

## 5.Model Building:

### 5.1 Train test split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y , test_size=0.20 ,shuffle=True)
X_train,X_test,y_train,y_test

(     CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 500     0.0       1.0       0.0    55.0  6.850
 370     0.0       1.0       0.0    59.0  0.000
 574     1.0       1.0       0.0    49.0  6.371
 258     0.0       1.0       0.0     0.0  0.709
 963     1.0       1.0       0.0     6.0  0.608
 ..      ...       ...       ...     ...    ...
 702     1.0       1.0       0.0    40.0  3.570
 662     1.0       1.0       0.0     0.0  0.005
 716     1.0       1.0       0.0    30.0  1.105
 382     1.0       1.0       0.0    35.0  8.508
 999     1.0       1.0       0.0    15.0  1.090

 [876 rows x 5 columns],
       CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
 1204     1.0       1.0       0.0     6.0  3.780
 553      1.0       0.0       0.0     3.0  0.579
 647      1.0       1.0       0.0    70.0  0.060
 885      1.0       1.0       0.0    11.0  4.115
 1118     0.0       1.0       0.0    30.0  1.816
 ...      ...       ...       ...     ...    ...
 757      0.0       1.0       0.0    39.0  3.741
 598      1.0       1.0       0.0     9.0  0.550
 661      1.0       1.0       0.0    41.0  9.160
 638      0.0       1.0       0.0    31.0  0.155
 590      1.0       1.0       0.0     6.0  0.100

 [220 rows x 5 columns],
      ATTORNEY
 500         0
 370         1
 574         0
 258         0
 963         1
 ..        ...
 702         0
 662         1
 716         0
 382         0
 999         1

 [876 rows x 1 columns],
       ATTORNEY
 1204         0
 553          0
 647          1
 885          0
 1118         0
 ...        ...
 757          0
 598          1
 661          1
 638          0
 590          1

 [220 rows x 1 columns])

In [12]:
X_train

     CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
500     0.0       1.0       0.0    55.0  6.850
370     0.0       1.0       0.0    59.0  0.000
574     1.0       1.0       0.0    49.0  6.371
258     0.0       1.0       0.0     0.0  0.709
963     1.0       1.0       0.0     6.0  0.608
..      ...       ...       ...     ...    ...
702     1.0       1.0       0.0    40.0  3.570
662     1.0       1.0       0.0     0.0  0.005
716     1.0       1.0       0.0    30.0  1.105
382     1.0       1.0       0.0    35.0  8.508
999     1.0       1.0       0.0    15.0  1.090

[876 rows x 5 columns]

In [13]:
logistic_model = LogisticRegression()
logistic_model

LogisticRegression()

## 6.Model Training:

In [18]:
logistic_model.fit(X_train,y_train)

LogisticRegression()

## 7.Model Testing:

y_pred = logistic_model.predict(X)
y_pred

#### Training data output: 80%

In [16]:
y_train_pred = logistic_model.predict(X_train)
y_train_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1])

#### Testing data output: 20%

In [19]:
y_test_pred = logistic_model.predict(X_test)
y_test_pred

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1])

In [21]:
###claimants_data["predicted_output"] = logistic_model.predict(X)
###claimants_data

## 8.Model evaluation

In [23]:
from sklearn.metrics import accuracy_score

### Training data accuracy

In [25]:
accuracy_score(y_train,y_train_pred)

0.702054794520548

### Testing data accuracy

In [26]:
accuracy_score(y_test,y_test_pred)

0.7272727272727273

## 9.Model deployment:

In [27]:
from pickle import dump

In [28]:
dump(obj=logistic_model,file= open(file=("claimaints.pkl"),mode ="wb"))

In [29]:
from pickle import load

In [30]:
logistic_intelligence_pickle_load = load(file = open(file="claimaints.pkl",mode="rb"))
logistic_intelligence_pickle_load

LogisticRegression()

In [38]:
logistic_intelligence_pickle_load.predict(X)

array([0, 1, 1, ..., 1, 0, 1], shape=(1096,))