## Environmental Dataset Description

 Environmental Dataset Description 
 General Atmospheric Standard KT

________________________________________

Ozone
Unit: Parts Per Billion (ppb)
Typical Range:
●	0–50 ppb → Good / Safe air quality
●	51–100 ppb → Moderate (sensitive people may feel irritation)
●	101+ ppb → Poor / unhealthy
Interpretation:
●	Low ozone: Clean air
●	High ozone: Air pollution, breathing discomfort, environmental risk
Ozone is a primary air-quality indicator.

Solar.R (Solar Radiation)
Unit: Watts per square meter (W/m²)
Typical Range:
●	0–100 → Very low sunlight (cloudy / evening)
●	100–300 → Moderate sunlight
●	300–400+ → Strong sunlight
Interpretation:
●	Low: Overcast / weak sun
●	High: Bright sunny day
Used to measure solar energy reaching Earth.

Wind
Unit: Miles per hour (mph)
Typical Range:
●	0–5 mph → Calm
●	5–15 mph → Light breeze
●	15–25 mph → Windy
●	25+ mph → Strong wind
Interpretation:
●	Low wind: Pollutants stay trapped
●	High wind: Pollutants disperse faster
Important for air circulation & pollution spread.

Temp C (Temperature in Celsius)
Unit: °C
Typical Range:
●	<10°C → Cold
●	10–25°C → Comfortable
●	25–35°C → Hot
●	35+°C → Extreme heat
Interpretation:
●	Low: Cold weather
●	High: Heat stress conditions
Primary climate variable.

Temp (Duplicate Column)
Appears identical to Temp C.
Most likely:
●	Redundant feature
●	Earlier Fahrenheit converted to Celsius
●	Export mistake

Month
Unit: Numeric (1–12)
Represents seasonal cycle
●	Lower months → winter / spring
●	Higher months → summer / autumn

Used for seasonality analysis.

Day
Unit: Numeric (1–31)
Represents calendar day
Used for:
●	Daily trend analysis
●	Time series sequencing

Year
Unit: Year number (example: 2010)
Represents temporal grouping

Weather (Categorical)
Values:
●	S → Sunny
●	PS → Partly Sunny
●	C → Cloudy
Represents sky condition
Used as a qualitative climate indicator.

## 1.Data collection

### Import libraries

In [1]:
import pandas as pd

### Import dataset

In [2]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 2.Data Understanding

In [3]:
weather_data.shape

(158, 10)

In [4]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [5]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

NOTE: dtypes should be numerical[ int64 / float64] not object because machine can understand numbers only

In [6]:
weather_data.describe(include="all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [7]:
weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [8]:
weather_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

## 3.Data preparation / Preprocessing


1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype
2. Data Transformation
- If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
- If data is DISCRETE = Label Encoder, One hot Encoder

### stage 1: Data cleaning - drop na , fillna , mean ,mode, changing dtype

In [9]:
weather_data.head(10)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S
5           6   28.0      NaN  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS
7           8   19.0     99.0  13.8     59     5    8  2010    59       C
8           9    8.0     19.0  20.1     61     5    9  2010    61      PS
9          10    NaN    194.0   8.6     69     5   10  2010    69       S

#### 1.Remove unwanted columns 
1.  Unnamed: 0 , Temp C	
2. axis = 1 means columns

In [10]:
weather_data.drop(labels = ["Unnamed: 0","Temp C"] , axis=1,inplace=True)

In [11]:
weather_data.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [12]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [13]:
38/158 #ozone

0.24050632911392406

#### As 24 % of data is Nan in ozone , so dropping this column. even we can use median mean calculation and fill those null values but here we have 24 % of data is null so removing

In [14]:
del weather_data["Ozone"]

In [15]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4        NaN  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

#### Solar.R

In [16]:
7/158 #solar R

0.04430379746835443

ONly 7 rows we have null values so doing computations

In [17]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [18]:
weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

Now applying the values to replace NAN in solar R

In [19]:
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x : x.fillna(x.mean()).round())
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [20]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [21]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

Dont perform any operations in output colums instead remove that rows

In [22]:
weather_data.dropna(inplace=True)

In [23]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

#### chaning datatype

In [24]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

#### Month should be int

In [25]:
weather_data["Month"].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [26]:
import warnings
warnings.filterwarnings("ignore")

In [27]:
weather_data["Month"].replace(to_replace="May",value= 5 ,inplace=True)

In [28]:
weather_data["Month"].unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [29]:
weather_data["Month"]=weather_data["Month"].astype("int")
weather_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [30]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

All input features are numerical now.

### Stage 2
Machine can understand only 0s and 1s ...  all input features are numerical but o/p is categorical so transforming that.

### 2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

#### 1.LABEL ENCODER:

* Encode target labels with value between 0 and n_classes-1.

* This transformer should be used to encode target values, *i.e.* `y`, and
not the input `X`.

In [34]:
weather_data

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

My weather_data is properly cleaned  i dont want to change anything on it . so i am taking copy of that data

In [32]:
weather_datacopy = weather_data.copy()
weather_datacopy

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [33]:
from sklearn.preprocessing import LabelEncoder
le_encoder = LabelEncoder()
weather_datacopy["Weather"]= le_encoder.fit_transform(weather_datacopy["Weather"])
weather_datacopy

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

Based on alphabetical order it gives label from 0 to n-1  { C - 0 ,PS -1 ,S -2}

In [35]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [36]:
weather_datacopy.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

#### 2.One hotencoder

This can be achieved by using any of the following 2 libraries:

- Pandas - pd.get_dummies()
- sklearn - OneHotEncoder()

One-Hot Encoding is a feature engineering technique used to convert categorical variables into binary (0 and 1) columns. Each unique category becomes a separate column, where 1 indicates the presence of that category and 0 indicates its absence. It is commonly used for nominal categorical data in machine learning.

##### 1.Pandas - pd.get_dummies()

Convert categorical variable into dummy/indicator variables.

Each variable is converted in as many 0/1 variables as there are different
values. Columns in the output are each named after a value; if the input is
a DataFrame, the name of the original variable is prepended to the value.

In [43]:
weather_datacopy1 = weather_data.copy()
weather_datacopy1

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

weather_datacopy1 = pd.get_dummies(weather_datacopy1,columns=["Weather"])
weather_datacopy1

In [44]:
weather_datacopy1 = pd.get_dummies(weather_datacopy1,columns=["Weather"],dtype=int)
weather_datacopy1

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

##### 2.sklearn - OneHotEncoder()

In [71]:
weather_datacopy2 = weather_data.copy()
weather_datacopy2

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [72]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
ohe = OneHotEncoder(sparse_output=False)
encoded= ohe.fit_transform(weather_datacopy2[["Weather"]])
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [74]:
encoded_weather_datacopy2 = pd.DataFrame(encoded,columns=ohe.get_feature_names_out(['Weather']))
encoded_weather_datacopy2

     Weather_C  Weather_PS  Weather_S
0          0.0         0.0        1.0
1          1.0         0.0        0.0
2          0.0         1.0        0.0
3          0.0         0.0        1.0
4          0.0         0.0        1.0
..         ...         ...        ...
150        1.0         0.0        0.0
151        0.0         1.0        0.0
152        0.0         0.0        1.0
153        0.0         0.0        1.0
154        1.0         0.0        0.0

[155 rows x 3 columns]

In [75]:
weather_datacopy2 = weather_datacopy2.drop('Weather', axis=1)

weather_datacopy2 = pd.concat(
    [weather_datacopy2, encoded_weather_datacopy2],
    axis=1
)

weather_datacopy2.head()

   Solar.R  Wind  Month  Day    Year  Temp  Weather_C  Weather_PS  Weather_S
0    190.0   7.4    5.0  1.0  2010.0  67.0        0.0         0.0        1.0
1    118.0   8.0    5.0  2.0  2010.0  72.0        1.0         0.0        0.0
2    149.0  12.6    5.0  3.0  2010.0  74.0        0.0         1.0        0.0
3    313.0  11.5    5.0  4.0  2010.0  62.0        0.0         0.0        1.0
4    193.0  14.3    5.0  5.0  2010.0  56.0        0.0         0.0        1.0

In [76]:
#del weather_datacopy2

**Why can't we store the encoded output in a single Weather column?**

Because the Weather column has three unique categories (C, PS, and S). **OneHotEncoder creates one binary column for each unique category.** A value of 1 indicates the presence of that category, while 0 indicates its absence.

### How to choose between label encoder and  one hot encoder ?

### Input feature:
Based on whether it is **Parametric or a Non Parametric Model**, we will choosing between LE or OHE.
* For **Parametric Models**[Linear or logistic reg] - better to go with **OHE.**
* For **Non-Parametric Models** [DT]- always go with **Label Encoding.**

### Output feature:
Always the output feature, it must be **Label Encoder.**